/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardSatTestsRouteImport } from './routes/dashboard/sat-tests'
import { Route as DashboardPracticeRouteImport } from './routes/dashboard/practice'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUploadsRouteImport } from './routes/admin/uploads'
import { Route as AdminTestsRouteImport } from './routes/admin/tests'
import { Route as AdminSuccessStoriesRouteImport } from './routes/admin/success-stories'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminContactRequestsRouteImport } from './routes/admin/contact-requests'
import { Route as DashboardSatRunnerAttemptIdRouteImport } from './routes/dashboard/sat-runner.$attemptId'
import { Route as DashboardSatResultAttemptIdRouteImport } from './routes/dashboard/sat-result.$attemptId'
import { Route as AdminReviewUploadUploadIdRouteImport } from './routes/admin/review-upload.$uploadId'

const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSatTestsRoute = DashboardSatTestsRouteImport.update({
  id: '/sat-tests',
  path: '/sat-tests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPracticeRoute = DashboardPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadsRoute = AdminUploadsRouteImport.update({
  id: '/admin/uploads',
  path: '/admin/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestsRoute = AdminTestsRouteImport.update({
  id: '/admin/tests',
  path: '/admin/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuccessStoriesRoute = AdminSuccessStoriesRouteImport.update({
  id: '/admin/success-stories',
  path: '/admin/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactRequestsRoute = AdminContactRequestsRouteImport.update({
  id: '/admin/contact-requests',
  path: '/admin/contact-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSatRunnerAttemptIdRoute =
  DashboardSatRunnerAttemptIdRouteImport.update({
    id: '/sat-runner/$attemptId',
    path: '/sat-runner/$attemptId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSatResultAttemptIdRoute =
  DashboardSatResultAttemptIdRouteImport.update({
    id: '/sat-result/$attemptId',
    path: '/sat-result/$attemptId',
    getParentRoute: () => DashboardRoute,
  } as any)
const AdminReviewUploadUploadIdRoute =
  AdminReviewUploadUploadIdRouteImport.update({
    id: '/admin/review-upload/$uploadId',
    path: '/admin/review-upload/$uploadId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/admin/contact-requests': typeof AdminContactRequestsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/success-stories': typeof AdminSuccessStoriesRoute
  '/admin/tests': typeof AdminTestsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/sat-tests': typeof DashboardSatTestsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/review-upload/$uploadId': typeof AdminReviewUploadUploadIdRoute
  '/dashboard/sat-result/$attemptId': typeof DashboardSatResultAttemptIdRoute
  '/dashboard/sat-runner/$attemptId': typeof DashboardSatRunnerAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/admin/contact-requests': typeof AdminContactRequestsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/success-stories': typeof AdminSuccessStoriesRoute
  '/admin/tests': typeof AdminTestsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/sat-tests': typeof DashboardSatTestsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/review-upload/$uploadId': typeof AdminReviewUploadUploadIdRoute
  '/dashboard/sat-result/$attemptId': typeof DashboardSatResultAttemptIdRoute
  '/dashboard/sat-runner/$attemptId': typeof DashboardSatRunnerAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/admin/contact-requests': typeof AdminContactRequestsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/success-stories': typeof AdminSuccessStoriesRoute
  '/admin/tests': typeof AdminTestsRoute
  '/admin/uploads': typeof AdminUploadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/sat-tests': typeof DashboardSatTestsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/review-upload/$uploadId': typeof AdminReviewUploadUploadIdRoute
  '/dashboard/sat-result/$attemptId': typeof DashboardSatResultAttemptIdRoute
  '/dashboard/sat-runner/$attemptId': typeof DashboardSatRunnerAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/contact'
    | '/dashboard'
    | '/subscriptions'
    | '/success-stories'
    | '/admin/contact-requests'
    | '/admin/questions'
    | '/admin/success-stories'
    | '/admin/tests'
    | '/admin/uploads'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/practice'
    | '/dashboard/sat-tests'
    | '/admin/'
    | '/dashboard/'
    | '/admin/review-upload/$uploadId'
    | '/dashboard/sat-result/$attemptId'
    | '/dashboard/sat-runner/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/contact'
    | '/subscriptions'
    | '/success-stories'
    | '/admin/contact-requests'
    | '/admin/questions'
    | '/admin/success-stories'
    | '/admin/tests'
    | '/admin/uploads'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/practice'
    | '/dashboard/sat-tests'
    | '/admin'
    | '/dashboard'
    | '/admin/review-upload/$uploadId'
    | '/dashboard/sat-result/$attemptId'
    | '/dashboard/sat-runner/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/contact'
    | '/dashboard'
    | '/subscriptions'
    | '/success-stories'
    | '/admin/contact-requests'
    | '/admin/questions'
    | '/admin/success-stories'
    | '/admin/tests'
    | '/admin/uploads'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/practice'
    | '/dashboard/sat-tests'
    | '/admin/'
    | '/dashboard/'
    | '/admin/review-upload/$uploadId'
    | '/dashboard/sat-result/$attemptId'
    | '/dashboard/sat-runner/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SubscriptionsRoute: typeof SubscriptionsRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  AdminContactRequestsRoute: typeof AdminContactRequestsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminSuccessStoriesRoute: typeof AdminSuccessStoriesRoute
  AdminTestsRoute: typeof AdminTestsRoute
  AdminUploadsRoute: typeof AdminUploadsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReviewUploadUploadIdRoute: typeof AdminReviewUploadUploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sat-tests': {
      id: '/dashboard/sat-tests'
      path: '/sat-tests'
      fullPath: '/dashboard/sat-tests'
      preLoaderRoute: typeof DashboardSatTestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/practice': {
      id: '/dashboard/practice'
      path: '/practice'
      fullPath: '/dashboard/practice'
      preLoaderRoute: typeof DashboardPracticeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/uploads': {
      id: '/admin/uploads'
      path: '/admin/uploads'
      fullPath: '/admin/uploads'
      preLoaderRoute: typeof AdminUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tests': {
      id: '/admin/tests'
      path: '/admin/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/success-stories': {
      id: '/admin/success-stories'
      path: '/admin/success-stories'
      fullPath: '/admin/success-stories'
      preLoaderRoute: typeof AdminSuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact-requests': {
      id: '/admin/contact-requests'
      path: '/admin/contact-requests'
      fullPath: '/admin/contact-requests'
      preLoaderRoute: typeof AdminContactRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sat-runner/$attemptId': {
      id: '/dashboard/sat-runner/$attemptId'
      path: '/sat-runner/$attemptId'
      fullPath: '/dashboard/sat-runner/$attemptId'
      preLoaderRoute: typeof DashboardSatRunnerAttemptIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sat-result/$attemptId': {
      id: '/dashboard/sat-result/$attemptId'
      path: '/sat-result/$attemptId'
      fullPath: '/dashboard/sat-result/$attemptId'
      preLoaderRoute: typeof DashboardSatResultAttemptIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/review-upload/$uploadId': {
      id: '/admin/review-upload/$uploadId'
      path: '/admin/review-upload/$uploadId'
      fullPath: '/admin/review-upload/$uploadId'
      preLoaderRoute: typeof AdminReviewUploadUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardPracticeRoute: typeof DashboardPracticeRoute
  DashboardSatTestsRoute: typeof DashboardSatTestsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSatResultAttemptIdRoute: typeof DashboardSatResultAttemptIdRoute
  DashboardSatRunnerAttemptIdRoute: typeof DashboardSatRunnerAttemptIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardPracticeRoute: DashboardPracticeRoute,
  DashboardSatTestsRoute: DashboardSatTestsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSatResultAttemptIdRoute: DashboardSatResultAttemptIdRoute,
  DashboardSatRunnerAttemptIdRoute: DashboardSatRunnerAttemptIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SubscriptionsRoute: SubscriptionsRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  AdminContactRequestsRoute: AdminContactRequestsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminSuccessStoriesRoute: AdminSuccessStoriesRoute,
  AdminTestsRoute: AdminTestsRoute,
  AdminUploadsRoute: AdminUploadsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReviewUploadUploadIdRoute: AdminReviewUploadUploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
